# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-Build

on:
  release:
    types:
      - published

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f docker/python/requirements.txt ]; then pip install -r docker/python/requirements.txt; fi

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWD }}
        
      - name: Get Version
        id: pversion
        run: |
          if [[ "${{ github.ref_name }}" =~ ^[.\|v][0-9]{1,}.[0-9]{1,}[.\|-][0-9]{1,} ]];then
            VERSION=${{ github.ref_name }}
          else
            VERSION="latest"
          fi
          echo "git_revision=$VERSION" >> $GITHUB_OUTPUT
        
      - name: Build Images
        id: build
        run: make docker-build IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }} VERSION=${{ steps.pversion.outputs.git_revision }}

      - name: Push Images
        run: make docker-push IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }} VERSION=${{ steps.pversion.outputs.git_revision }}
